import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { ApiService } from 'app/services/api.service';
import { ControllerFormsComponent } from '../controller-forms.Component';
import { MatDialog } from '@angular/material/dialog';
@Component({
  selector: 'app-sglc25',
  templateUrl: './sglc25.component.html',
  styleUrls: ['./sglc25.component.scss']
})
export class Sglc25Component  extends ControllerFormsComponent  implements OnInit {

    override code = 'SG-LC-25';
    override id = this.activatedRouter.snapshot?.paramMap.get('id');
    image: string  = './assets/images/forms/sglc25.png';

    constructor(protected router: Router,
        protected _formBuilder: FormBuilder,
        protected activatedRouter: ActivatedRoute,
        protected matDialog: MatDialog,
        protected api: ApiService
    ) {
        super(_formBuilder, matDialog, api);
    }

    override ngOnInit(): void {
        super.ngOnInit();
        this.validateForm();
        this.getProject();
        this.getEmployees();
    }

    validateForm(): void {
        this.formInit = this._formBuilder.group({
            code: new FormControl(this.code),
            uid: new FormControl(),
            name: new FormControl(this.title),
            version: new FormControl('1.0'),
            company: new FormControl(1),
            fields: new FormArray([
                this._formBuilder.group({ name: 'location', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'operatorName', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'brand', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'serial', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'manufacturingModel', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'inspectionResult', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'observations', value:   '', type: this.getTypeValue(1) }),

                this._formBuilder.group({ name: 'switchPositionBeforePluggingMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'freeAdjustmentToolsFixedWrenchesMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerToolPlugCcorresponds220VMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'lockButtonGoodConditionMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'forwardReverseSlidingGuideWorksMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'equipmentFreeWaterMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'drillingModeSelectorWorksMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'chuckWorksMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'depthStopWorksMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'mandrillGoodConditionMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'hasKeyOpenCloseChuckMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerSwitchWorksCorrectlyMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'plugisGoodConditionWireMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'multiPositionSideHandleGoodConditionMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionWiringUncutGoodConditionMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'eyeProtectionRespiratoryHearingMonday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'switchPositionBeforePluggingTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'freeAdjustmentToolsFixedWrenchesTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerToolPlugCcorresponds220VTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'lockButtonGoodConditionTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'forwardReverseSlidingGuideWorksTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'equipmentFreeWaterTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'drillingModeSelectorWorksTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'chuckWorksTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'depthStopWorksTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'mandrillGoodConditionTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'hasKeyOpenCloseChuckTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerSwitchWorksCorrectlyTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'plugisGoodConditionWireTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'multiPositionSideHandleGoodConditionTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionWiringUncutGoodConditionTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'eyeProtectionRespiratoryHearingTuesday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'switchPositionBeforePluggingWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'freeAdjustmentToolsFixedWrenchesWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerToolPlugCcorresponds220VWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'lockButtonGoodConditionWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'forwardReverseSlidingGuideWorksWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'equipmentFreeWaterWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'drillingModeSelectorWorksWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'chuckWorksWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'depthStopWorksWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'mandrillGoodConditionWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'hasKeyOpenCloseChuckWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerSwitchWorksCorrectlyWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'plugisGoodConditionWireWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'multiPositionSideHandleGoodConditionWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionWiringUncutGoodConditionWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'eyeProtectionRespiratoryHearingWednesday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'switchPositionBeforePluggingThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'freeAdjustmentToolsFixedWrenchesThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerToolPlugCcorresponds220VThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'lockButtonGoodConditionThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'forwardReverseSlidingGuideWorksThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'equipmentFreeWaterThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'drillingModeSelectorWorksThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'chuckWorksThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'depthStopWorksThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'mandrillGoodConditionThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'hasKeyOpenCloseChuckThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerSwitchWorksCorrectlyThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'plugisGoodConditionWireThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'multiPositionSideHandleGoodConditionThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionWiringUncutGoodConditionThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'eyeProtectionRespiratoryHearingThursday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'switchPositionBeforePluggingFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'freeAdjustmentToolsFixedWrenchesFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerToolPlugCcorresponds220VFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'lockButtonGoodConditionFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'forwardReverseSlidingGuideWorksFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'equipmentFreeWaterFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'drillingModeSelectorWorksFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'chuckWorksFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'depthStopWorksFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'mandrillGoodConditionFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'hasKeyOpenCloseChuckFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerSwitchWorksCorrectlyFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'plugisGoodConditionWireFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'multiPositionSideHandleGoodConditionFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionWiringUncutGoodConditionFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'eyeProtectionRespiratoryHearingFriday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'switchPositionBeforePluggingSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'freeAdjustmentToolsFixedWrenchesSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerToolPlugCcorresponds220VSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'lockButtonGoodConditionSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'forwardReverseSlidingGuideWorksSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'equipmentFreeWaterSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'drillingModeSelectorWorksSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'chuckWorksSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'depthStopWorksSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'mandrillGoodConditionSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'hasKeyOpenCloseChuckSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerSwitchWorksCorrectlySaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'plugisGoodConditionWireSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'multiPositionSideHandleGoodConditionSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionWiringUncutGoodConditionSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'eyeProtectionRespiratoryHearingSaturday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'switchPositionBeforePluggingSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'freeAdjustmentToolsFixedWrenchesSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerToolPlugCcorresponds220VSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'lockButtonGoodConditionSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'forwardReverseSlidingGuideWorksSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'equipmentFreeWaterSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'drillingModeSelectorWorksSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'chuckWorksSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'depthStopWorksSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'mandrillGoodConditionSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'hasKeyOpenCloseChuckSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'powerSwitchWorksCorrectlySunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'plugisGoodConditionWireSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'multiPositionSideHandleGoodConditionSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionWiringUncutGoodConditionSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'eyeProtectionRespiratoryHearingSunday', value:   '', type: this.getTypeValue(5) }),

            ]),
            evidences: new FormControl([]),
            project: new FormControl('', [Validators.required]),
            assistants: new FormControl([]),
            approval: new FormControl([]),
            fieldsItems: this._formBuilder.group({
                location: new FormControl(''),
                operatorName: new FormControl(''),
                brand: new FormControl(''),
                serial: new FormControl(''),
                manufacturingModel: new FormControl(''),
                inspectionResult: new FormControl(),
                observations: new FormControl(''),

                switchPositionBeforePluggingMonday: new FormControl(),
                freeAdjustmentToolsFixedWrenchesMonday: new FormControl(),
                powerToolPlugCcorresponds220VMonday: new FormControl(),
                lockButtonGoodConditionMonday: new FormControl(),
                forwardReverseSlidingGuideWorksMonday: new FormControl(),
                equipmentFreeWaterMonday: new FormControl(),
                drillingModeSelectorWorksMonday: new FormControl(),
                chuckWorksMonday: new FormControl(),
                depthStopWorksMonday: new FormControl(),
                mandrillGoodConditionMonday: new FormControl(),
                hasKeyOpenCloseChuckMonday: new FormControl(),
                powerSwitchWorksCorrectlyMonday: new FormControl(),
                plugisGoodConditionWireMonday: new FormControl(),
                multiPositionSideHandleGoodConditionMonday: new FormControl(),
                connectionWiringUncutGoodConditionMonday: new FormControl(),
                eyeProtectionRespiratoryHearingMonday: new FormControl(),

                switchPositionBeforePluggingTuesday: new FormControl(),
                freeAdjustmentToolsFixedWrenchesTuesday: new FormControl(),
                powerToolPlugCcorresponds220VTuesday: new FormControl(),
                lockButtonGoodConditionTuesday: new FormControl(),
                forwardReverseSlidingGuideWorksTuesday: new FormControl(),
                equipmentFreeWaterTuesday: new FormControl(),
                drillingModeSelectorWorksTuesday: new FormControl(),
                chuckWorksTuesday: new FormControl(),
                depthStopWorksTuesday: new FormControl(),
                mandrillGoodConditionTuesday: new FormControl(),
                hasKeyOpenCloseChuckTuesday: new FormControl(),
                powerSwitchWorksCorrectlyTuesday: new FormControl(),
                plugisGoodConditionWireTuesday: new FormControl(),
                multiPositionSideHandleGoodConditionTuesday: new FormControl(),
                connectionWiringUncutGoodConditionTuesday: new FormControl(),
                eyeProtectionRespiratoryHearingTuesday: new FormControl(),


                switchPositionBeforePluggingWednesday: new FormControl(),
                freeAdjustmentToolsFixedWrenchesWednesday: new FormControl(),
                powerToolPlugCcorresponds220VWednesday: new FormControl(),
                lockButtonGoodConditionWednesday: new FormControl(),
                forwardReverseSlidingGuideWorksWednesday: new FormControl(),
                equipmentFreeWaterWednesday: new FormControl(),
                drillingModeSelectorWorksWednesday: new FormControl(),
                chuckWorksWednesday: new FormControl(),
                depthStopWorksWednesday: new FormControl(),
                mandrillGoodConditionWednesday: new FormControl(),
                hasKeyOpenCloseChuckWednesday: new FormControl(),
                powerSwitchWorksCorrectlyWednesday: new FormControl(),
                plugisGoodConditionWireWednesday: new FormControl(),
                multiPositionSideHandleGoodConditionWednesday: new FormControl(),
                connectionWiringUncutGoodConditionWednesday: new FormControl(),
                eyeProtectionRespiratoryHearingWednesday: new FormControl(),

                switchPositionBeforePluggingThursday: new FormControl(),
                freeAdjustmentToolsFixedWrenchesThursday: new FormControl(),
                powerToolPlugCcorresponds220VThursday: new FormControl(),
                lockButtonGoodConditionThursday: new FormControl(),
                forwardReverseSlidingGuideWorksThursday: new FormControl(),
                equipmentFreeWaterThursday: new FormControl(),
                drillingModeSelectorWorksThursday: new FormControl(),
                chuckWorksThursday: new FormControl(),
                depthStopWorksThursday: new FormControl(),
                mandrillGoodConditionThursday: new FormControl(),
                hasKeyOpenCloseChuckThursday: new FormControl(),
                powerSwitchWorksCorrectlyThursday: new FormControl(),
                plugisGoodConditionWireThursday: new FormControl(),
                multiPositionSideHandleGoodConditionThursday: new FormControl(),
                connectionWiringUncutGoodConditionThursday: new FormControl(),
                eyeProtectionRespiratoryHearingThursday: new FormControl(),

                switchPositionBeforePluggingFriday: new FormControl(),
                freeAdjustmentToolsFixedWrenchesFriday: new FormControl(),
                powerToolPlugCcorresponds220VFriday: new FormControl(),
                lockButtonGoodConditionFriday: new FormControl(),
                forwardReverseSlidingGuideWorksFriday: new FormControl(),
                equipmentFreeWaterFriday: new FormControl(),
                drillingModeSelectorWorksFriday: new FormControl(),
                chuckWorksFriday: new FormControl(),
                depthStopWorksFriday: new FormControl(),
                mandrillGoodConditionFriday: new FormControl(),
                hasKeyOpenCloseChuckFriday: new FormControl(),
                powerSwitchWorksCorrectlyFriday: new FormControl(),
                plugisGoodConditionWireFriday: new FormControl(),
                multiPositionSideHandleGoodConditionFriday: new FormControl(),
                connectionWiringUncutGoodConditionFriday: new FormControl(),
                eyeProtectionRespiratoryHearingFriday: new FormControl(),

                switchPositionBeforePluggingSaturday: new FormControl(),
                freeAdjustmentToolsFixedWrenchesSaturday: new FormControl(),
                powerToolPlugCcorresponds220VSaturday: new FormControl(),
                lockButtonGoodConditionSaturday: new FormControl(),
                forwardReverseSlidingGuideWorksSaturday: new FormControl(),
                equipmentFreeWaterSaturday: new FormControl(),
                drillingModeSelectorWorksSaturday: new FormControl(),
                chuckWorksSaturday: new FormControl(),
                depthStopWorksSaturday: new FormControl(),
                mandrillGoodConditionSaturday: new FormControl(),
                hasKeyOpenCloseChuckSaturday: new FormControl(),
                powerSwitchWorksCorrectlySaturday: new FormControl(),
                plugisGoodConditionWireSaturday: new FormControl(),
                multiPositionSideHandleGoodConditionSaturday: new FormControl(),
                connectionWiringUncutGoodConditionSaturday: new FormControl(),
                eyeProtectionRespiratoryHearingSaturday: new FormControl(),

                switchPositionBeforePluggingSunday: new FormControl(),
                freeAdjustmentToolsFixedWrenchesSunday: new FormControl(),
                powerToolPlugCcorresponds220VSunday: new FormControl(),
                lockButtonGoodConditionSunday: new FormControl(),
                forwardReverseSlidingGuideWorksSunday: new FormControl(),
                equipmentFreeWaterSunday: new FormControl(),
                drillingModeSelectorWorksSunday: new FormControl(),
                chuckWorksSunday: new FormControl(),
                depthStopWorksSunday: new FormControl(),
                mandrillGoodConditionSunday: new FormControl(),
                hasKeyOpenCloseChuckSunday: new FormControl(),
                powerSwitchWorksCorrectlySunday: new FormControl(),
                plugisGoodConditionWireSunday: new FormControl(),
                multiPositionSideHandleGoodConditionSunday: new FormControl(),
                connectionWiringUncutGoodConditionSunday: new FormControl(),
                eyeProtectionRespiratoryHearingSunday: new FormControl(),
            }),
            filesUpload: new FormControl(),
            assignedAssistants: new FormControl(),
            trainingApproval: new FormControl()
        });
    }

    override getForm(): void {
        if (this.id) {
            this.formInit.get('fieldsItems').patchValue({
                location: this.cleanSelect(this.getValueField('location')),
                operatorName: this.cleanSelect(this.getValueField('operatorName')),
                brand: this.cleanSelect(this.getValueField('brand')),
                serial: this.cleanSelect(this.getValueField('serial')),
                manufacturingModel: this.cleanSelect(this.getValueField('manufacturingModel')),
                inspectionResult: this.cleanSelect(this.getValueField('inspectionResult')),
                observations: this.cleanSelect(this.getValueField('observations')),

                switchPositionBeforePluggingMonday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingMonday')),
                freeAdjustmentToolsFixedWrenchesMonday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesMonday')),
                powerToolPlugCcorresponds220VMonday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VMonday')),
                lockButtonGoodConditionMonday: this.cleanSelect(this.getValueField('lockButtonGoodConditionMonday')),
                forwardReverseSlidingGuideWorksMonday: this.cleanSelect(this.getValueField('forwardReverseSlidingGuideWorksMonday')),
                equipmentFreeWaterMonday: this.cleanSelect(this.getValueField('equipmentFreeWaterMonday')),
                drillingModeSelectorWorksMonday: this.cleanSelect(this.getValueField('drillingModeSelectorWorksMonday')),
                chuckWorksMonday: this.cleanSelect(this.getValueField('chuckWorksMonday')),
                depthStopWorksMonday: this.cleanSelect(this.getValueField('depthStopWorksMonday')),
                mandrillGoodConditionMonday: this.cleanSelect(this.getValueField('mandrillGoodConditionMonday')),
                hasKeyOpenCloseChuckMonday: this.cleanSelect(this.getValueField('hasKeyOpenCloseChuckMonday')),
                powerSwitchWorksCorrectlyMonday: this.cleanSelect(this.getValueField('powerSwitchWorksCorrectlyMonday')),
                plugisGoodConditionWireMonday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingMonday')),
                multiPositionSideHandleGoodConditionMonday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesMonday')),
                connectionWiringUncutGoodConditionMonday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VMonday')),
                eyeProtectionRespiratoryHearingMonday: this.cleanSelect(this.getValueField('lockButtonGoodConditionMonday')),

                switchPositionBeforePluggingTuesday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingTuesday')),
                freeAdjustmentToolsFixedWrenchesTuesday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesTuesday')),
                powerToolPlugCcorresponds220VTuesday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VTuesday')),
                lockButtonGoodConditionTuesday: this.cleanSelect(this.getValueField('lockButtonGoodConditionTuesday')),
                forwardReverseSlidingGuideWorksTuesday: this.cleanSelect(this.getValueField('forwardReverseSlidingGuideWorksTuesday')),
                equipmentFreeWaterTuesday: this.cleanSelect(this.getValueField('equipmentFreeWaterTuesday')),
                drillingModeSelectorWorksTuesday: this.cleanSelect(this.getValueField('drillingModeSelectorWorksTuesday')),
                chuckWorksTuesday: this.cleanSelect(this.getValueField('chuckWorksTuesday')),
                depthStopWorksTuesday: this.cleanSelect(this.getValueField('depthStopWorksTuesday')),
                mandrillGoodConditionTuesday: this.cleanSelect(this.getValueField('mandrillGoodConditionTuesday')),
                hasKeyOpenCloseChuckTuesday: this.cleanSelect(this.getValueField('hasKeyOpenCloseChuckTuesday')),
                powerSwitchWorksCorrectlyTuesday: this.cleanSelect(this.getValueField('powerSwitchWorksCorrectlyTuesday')),
                plugisGoodConditionWireTuesday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingTuesday')),
                multiPositionSideHandleGoodConditionTuesday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesTuesday')),
                connectionWiringUncutGoodConditionTuesday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VTuesday')),
                eyeProtectionRespiratoryHearingTuesday: this.cleanSelect(this.getValueField('lockButtonGoodConditionTuesday')),

                switchPositionBeforePluggingWednesday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingWednesday')),
                freeAdjustmentToolsFixedWrenchesWednesday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesWednesday')),
                powerToolPlugCcorresponds220VWednesday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VWednesday')),
                lockButtonGoodConditionWednesday: this.cleanSelect(this.getValueField('lockButtonGoodConditionWednesday')),
                forwardReverseSlidingGuideWorksWednesday: this.cleanSelect(this.getValueField('forwardReverseSlidingGuideWorksWednesday')),
                equipmentFreeWaterWednesday: this.cleanSelect(this.getValueField('equipmentFreeWaterWednesday')),
                drillingModeSelectorWorksWednesday: this.cleanSelect(this.getValueField('drillingModeSelectorWorksWednesday')),
                chuckWorksWednesday: this.cleanSelect(this.getValueField('chuckWorksWednesday')),
                depthStopWorksWednesday: this.cleanSelect(this.getValueField('depthStopWorksWednesday')),
                mandrillGoodConditionWednesday: this.cleanSelect(this.getValueField('mandrillGoodConditionWednesday')),
                hasKeyOpenCloseChuckWednesday: this.cleanSelect(this.getValueField('hasKeyOpenCloseChuckWednesday')),
                powerSwitchWorksCorrectlyWednesday: this.cleanSelect(this.getValueField('powerSwitchWorksCorrectlyWednesday')),
                plugisGoodConditionWireWednesday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingWednesday')),
                multiPositionSideHandleGoodConditionWednesday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesWednesday')),
                connectionWiringUncutGoodConditionWednesday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VWednesday')),
                eyeProtectionRespiratoryHearingWednesday: this.cleanSelect(this.getValueField('lockButtonGoodConditionWednesday')),

                switchPositionBeforePluggingThursday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingThursday')),
                freeAdjustmentToolsFixedWrenchesThursday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesThursday')),
                powerToolPlugCcorresponds220VThursday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VThursday')),
                lockButtonGoodConditionThursday: this.cleanSelect(this.getValueField('lockButtonGoodConditionThursday')),
                forwardReverseSlidingGuideWorksThursday: this.cleanSelect(this.getValueField('forwardReverseSlidingGuideWorksThursday')),
                equipmentFreeWaterThursday: this.cleanSelect(this.getValueField('equipmentFreeWaterThursday')),
                drillingModeSelectorWorksThursday: this.cleanSelect(this.getValueField('drillingModeSelectorWorksThursday')),
                chuckWorksThursday: this.cleanSelect(this.getValueField('chuckWorksThursday')),
                depthStopWorksThursday: this.cleanSelect(this.getValueField('depthStopWorksThursday')),
                mandrillGoodConditionThursday: this.cleanSelect(this.getValueField('mandrillGoodConditionThursday')),
                hasKeyOpenCloseChuckThursday: this.cleanSelect(this.getValueField('hasKeyOpenCloseChuckThursday')),
                powerSwitchWorksCorrectlyThursday: this.cleanSelect(this.getValueField('powerSwitchWorksCorrectlyThursday')),
                plugisGoodConditionWireThursday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingThursday')),
                multiPositionSideHandleGoodConditionThursday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesThursday')),
                connectionWiringUncutGoodConditionThursday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VThursday')),
                eyeProtectionRespiratoryHearingThursday: this.cleanSelect(this.getValueField('lockButtonGoodConditionThursday')),

                switchPositionBeforePluggingFriday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingFriday')),
                freeAdjustmentToolsFixedWrenchesFriday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesFriday')),
                powerToolPlugCcorresponds220VFriday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VFriday')),
                lockButtonGoodConditionFriday: this.cleanSelect(this.getValueField('lockButtonGoodConditionFriday')),
                forwardReverseSlidingGuideWorksFriday: this.cleanSelect(this.getValueField('forwardReverseSlidingGuideWorksFriday')),
                equipmentFreeWaterFriday: this.cleanSelect(this.getValueField('equipmentFreeWaterFriday')),
                drillingModeSelectorWorksFriday: this.cleanSelect(this.getValueField('drillingModeSelectorWorksFriday')),
                chuckWorksFriday: this.cleanSelect(this.getValueField('chuckWorksFriday')),
                depthStopWorksFriday: this.cleanSelect(this.getValueField('depthStopWorksFriday')),
                mandrillGoodConditionFriday: this.cleanSelect(this.getValueField('mandrillGoodConditionFriday')),
                hasKeyOpenCloseChuckFriday: this.cleanSelect(this.getValueField('hasKeyOpenCloseChuckFriday')),
                powerSwitchWorksCorrectlyFriday: this.cleanSelect(this.getValueField('powerSwitchWorksCorrectlyFriday')),
                plugisGoodConditionWireFriday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingFriday')),
                multiPositionSideHandleGoodConditionFriday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesFriday')),
                connectionWiringUncutGoodConditionFriday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VFriday')),
                eyeProtectionRespiratoryHearingFriday: this.cleanSelect(this.getValueField('lockButtonGoodConditionFriday')),

                switchPositionBeforePluggingSaturday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingSaturday')),
                freeAdjustmentToolsFixedWrenchesSaturday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesSaturday')),
                powerToolPlugCcorresponds220VSaturday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VSaturday')),
                lockButtonGoodConditionSaturday: this.cleanSelect(this.getValueField('lockButtonGoodConditionSaturday')),
                forwardReverseSlidingGuideWorksSaturday: this.cleanSelect(this.getValueField('forwardReverseSlidingGuideWorksSaturday')),
                equipmentFreeWaterSaturday: this.cleanSelect(this.getValueField('equipmentFreeWaterSaturday')),
                drillingModeSelectorWorksSaturday: this.cleanSelect(this.getValueField('drillingModeSelectorWorksSaturday')),
                chuckWorksSaturday: this.cleanSelect(this.getValueField('chuckWorksSaturday')),
                depthStopWorksSaturday: this.cleanSelect(this.getValueField('depthStopWorksSaturday')),
                mandrillGoodConditionSaturday: this.cleanSelect(this.getValueField('mandrillGoodConditionSaturday')),
                hasKeyOpenCloseChuckSaturday: this.cleanSelect(this.getValueField('hasKeyOpenCloseChuckSaturday')),
                powerSwitchWorksCorrectlySaturday: this.cleanSelect(this.getValueField('powerSwitchWorksCorrectlySaturday')),
                plugisGoodConditionWireSaturday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingSaturday')),
                multiPositionSideHandleGoodConditionSaturday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesSaturday')),
                connectionWiringUncutGoodConditionSaturday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VSaturday')),
                eyeProtectionRespiratoryHearingSaturday: this.cleanSelect(this.getValueField('lockButtonGoodConditionSaturday')),

                switchPositionBeforePluggingSunday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingSunday')),
                freeAdjustmentToolsFixedWrenchesSunday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesSunday')),
                powerToolPlugCcorresponds220VSunday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VSunday')),
                lockButtonGoodConditionSunday: this.cleanSelect(this.getValueField('lockButtonGoodConditionSunday')),
                forwardReverseSlidingGuideWorksSunday: this.cleanSelect(this.getValueField('forwardReverseSlidingGuideWorksSunday')),
                equipmentFreeWaterSunday: this.cleanSelect(this.getValueField('equipmentFreeWaterSunday')),
                drillingModeSelectorWorksSunday: this.cleanSelect(this.getValueField('drillingModeSelectorWorksSunday')),
                chuckWorksSunday: this.cleanSelect(this.getValueField('chuckWorksSunday')),
                depthStopWorksSunday: this.cleanSelect(this.getValueField('depthStopWorksSunday')),
                mandrillGoodConditionSunday: this.cleanSelect(this.getValueField('mandrillGoodConditionSunday')),
                hasKeyOpenCloseChuckSunday: this.cleanSelect(this.getValueField('hasKeyOpenCloseChuckSunday')),
                powerSwitchWorksCorrectlySunday: this.cleanSelect(this.getValueField('powerSwitchWorksCorrectlySunday')),
                plugisGoodConditionWireSunday: this.cleanSelect(this.getValueField('switchPositionBeforePluggingSunday')),
                multiPositionSideHandleGoodConditionSunday: this.cleanSelect(this.getValueField('freeAdjustmentToolsFixedWrenchesSunday')),
                connectionWiringUncutGoodConditionSunday: this.cleanSelect(this.getValueField('powerToolPlugCcorresponds220VSunday')),
                eyeProtectionRespiratoryHearingSunday: this.cleanSelect(this.getValueField('lockButtonGoodConditionSunday')),
            });
        }
    }

    filterParamLabel(param): void{
        return this.getLabel(param);
    }

    filterParamValue(param): void{
        return this.getParamLabel(param);
    }

    onSubmit(): void {
        this.validationSubmit();
    }
}
