import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { ApiService } from 'app/services/api.service';
import { ControllerFormsComponent } from '../controller-forms.Component';
import { MatDialog } from '@angular/material/dialog';

@Component({
    selector: 'app-sglc04',
    templateUrl: './sglc04.component.html',
    styleUrls: ['./sglc04.component.scss']
})
export class Sglc04Component extends ControllerFormsComponent implements OnInit {

    override code = 'SG-LC-04';
    override id = this.activatedRouter.snapshot?.paramMap.get('id');

    constructor(protected router: Router,
        protected _formBuilder: FormBuilder,
        protected activatedRouter: ActivatedRoute,
        protected matDialog: MatDialog,
        protected api: ApiService
    ) {
        super(_formBuilder, matDialog, api);
    }

    override ngOnInit(): void {
        super.ngOnInit();
        this.validateForm();
        this.getProject();
        this.getToolsInspectionStatus();
        this.getEmployees();
    }

    validateForm(): void {
        this.formInit = this._formBuilder.group({
            code: new FormControl(this.code),
            uid: new FormControl(),
            name: new FormControl(this.title),
            version: new FormControl('1.0'),
            company: new FormControl(1),
            fields: new FormArray([
                this._formBuilder.group({ name: 'emery', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'drill', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'press', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'compressor', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'weldingMachine', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'polisher', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'employee', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'gasCuttingEquipment', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'handsaw', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'vibrocompactador', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'mixer', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'submersiblePump', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'pressureWasher', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'doubleHandleHammerDrill', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'marshland', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'singleDrillA', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'sander', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'smallPolisherA', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'largePolisherB', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'shears', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'bigHammer', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'hammers', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'knives', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'fixedLadder', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'machete', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'gusts', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'drillBits', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'fixedWrenches', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'electricalTweezers', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'needleNoseTweezers', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'screwdrivers', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'decameters', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'tapeMeasures', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'needleNosePlierss', value: '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'emeryObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'drillObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'pressObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'compressorObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'weldingMachineObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'polisherObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'gasCuttingEquipmentObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'handsawObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'vibrocompactadorObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'mixerObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'submersiblePumpObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'pressureWasherObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'doubleHandleHammerDrillObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'marshlandObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'singleDrillAObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'sanderObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'smallPolisherAObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'largePolisherBObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'shearsObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'bigHammerObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'hammersObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'knivesObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'fixedLadderObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'macheteObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'gustsObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'drillBitsObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'fixedWrenchesObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'electricalTweezersObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'needleNoseTweezersObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'screwdriversObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'decametersObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'tapeMeasuresObserv', value: '', type: this.getTypeValue(9) }),
                this._formBuilder.group({ name: 'needleNosePlierssObserv', value: '', type: this.getTypeValue(9) })
            ]),
            evidences: new FormControl([]),
            project: new FormControl(''),
            assistants: new FormControl([]),
            approval: new FormControl([]),
            fieldsItems: this._formBuilder.group({
                emery: new FormControl(),
                drill: new FormControl(''),
                press: new FormControl(''),
                compressor: new FormControl(''),
                weldingMachine: new FormControl(''),
                polisher: new FormControl(''),
                employee: new FormControl(''),
                gasCuttingEquipment: new FormControl(''),
                handsaw: new FormControl(''),
                vibrocompactador: new FormControl(''),
                mixer: new FormControl(''),
                submersiblePump: new FormControl(''),
                pressureWasher: new FormControl(''),
                doubleHandleHammerDrill: new FormControl(''),
                marshland: new FormControl(''),
                singleDrillA: new FormControl(''),
                sander: new FormControl(''),
                smallPolisherA: new FormControl(),
                largePolisherB: new FormControl(''),
                shears: new FormControl(''),
                bigHammer: new FormControl(''),
                hammers: new FormControl(''),
                knives: new FormControl(),
                fixedLadder: new FormControl(),
                machete: new FormControl(),
                gusts: new FormControl(),
                drillBits: new FormControl(),
                fixedWrenches: new FormControl(),
                electricalTweezers: new FormControl(''),
                needleNoseTweezers: new FormControl(''),
                screwdrivers: new FormControl(''),
                decameters: new FormControl(),
                tapeMeasures: new FormControl(),
                needleNosePlierss: new FormControl(),
                emeryObserv: new FormControl(),
                drillObserv: new FormControl(''),
                pressObserv: new FormControl(''),
                compressorObserv: new FormControl(''),
                weldingMachineObserv: new FormControl(''),
                polisherObserv: new FormControl(''),
                gasCuttingEquipmentObserv: new FormControl(''),
                handsawObserv: new FormControl(''),
                vibrocompactadorObserv: new FormControl(''),
                mixerObserv: new FormControl(''),
                submersiblePumpObserv: new FormControl(''),
                pressureWasherObserv: new FormControl(''),
                doubleHandleHammerDrillObserv: new FormControl(''),
                marshlandObserv: new FormControl(''),
                singleDrillAObserv: new FormControl(''),
                sanderObserv: new FormControl(''),
                smallPolisherAObserv: new FormControl(),
                largePolisherBObserv: new FormControl(''),
                shearsObserv: new FormControl(''),
                bigHammerObserv: new FormControl(''),
                hammersObserv: new FormControl(''),
                knivesObserv: new FormControl(),
                fixedLadderObserv: new FormControl(),
                macheteObserv: new FormControl(),
                gustsObserv: new FormControl(),
                drillBitsObserv: new FormControl(),
                fixedWrenchesObserv: new FormControl(),
                electricalTweezersObserv: new FormControl(''),
                needleNoseTweezersObserv: new FormControl(''),
                screwdriversObserv: new FormControl(''),
                decametersObserv: new FormControl(),
                tapeMeasuresObserv: new FormControl(),
                needleNosePlierssObserv: new FormControl(),
            }),
            filesUpload: new FormControl(),
            assignedAssistants: new FormControl(),
            trainingApproval: new FormControl()
        });
    }


    override getForm(): void {
        if (this.id) {
            this.formInit.get('fieldsItems').patchValue({
                emery: this.cleanSelect(this.getValueField('emery')),
                drill: this.cleanSelect(this.getValueField('drill')),
                press: this.cleanSelect(this.getValueField('press')),
                compressor: this.cleanSelect(this.getValueField('compressor')),
                weldingMachine: this.cleanSelect(this.getValueField('weldingMachine')),
                polisher: this.cleanSelect(this.getValueField('polisher')),
                employee: this.cleanSelect(this.getValueField('employee')),
                gasCuttingEquipment: this.cleanSelect(this.getValueField('gasCuttingEquipment')),
                handsaw: this.cleanSelect(this.getValueField('handsaw')),
                vibrocompactador: this.cleanSelect(this.getValueField('vibrocompactador')),
                mixer: this.cleanSelect(this.getValueField('mixer')),
                submersiblePump: this.cleanSelect(this.getValueField('submersiblePump')),
                pressureWasher: this.cleanSelect(this.getValueField('pressureWasher')),
                doubleHandleHammerDrill: this.cleanSelect(this.getValueField('doubleHandleHammerDrill')),
                marshland: this.cleanSelect(this.getValueField('marshland')),
                singleDrillA: this.cleanSelect(this.getValueField('singleDrillA')),
                sander: this.cleanSelect(this.getValueField('sander')),
                smallPolisherA: this.cleanSelect(this.getValueField('smallPolisherA')),
                largePolisherB: this.cleanSelect(this.getValueField('largePolisherB')),
                shears: this.cleanSelect(this.getValueField('shears')),
                bigHammer: this.cleanSelect(this.getValueField('bigHammer')),
                hammers: this.cleanSelect(this.getValueField('hammers')),
                knives: this.cleanSelect(this.getValueField('knives')),
                fixedLadder: this.cleanSelect(this.getValueField('fixedLadder')),
                machete: this.cleanSelect(this.getValueField('machete')),
                gusts: this.cleanSelect(this.getValueField('gusts')),
                drillBits: this.cleanSelect(this.getValueField('drillBits')),
                fixedWrenches: this.cleanSelect(this.getValueField('fixedWrenches')),
                electricalTweezers: this.cleanSelect(this.getValueField('electricalTweezers')),
                needleNoseTweezers: this.cleanSelect(this.getValueField('needleNoseTweezers')),
                screwdrivers: this.cleanSelect(this.getValueField('screwdrivers')),
                decameters: this.cleanSelect(this.getValueField('fixedLadder')),
                tapeMeasures: this.cleanSelect(this.getValueField('tapeMeasures')),
                needleNosePlierss: this.cleanSelect(this.getValueField('tapeMeasures')),
                emeryObserv: this.cleanSelect(this.getValueField('emery')),
                drillObserv: this.cleanSelect(this.getValueField('drill')),
                pressObserv: this.cleanSelect(this.getValueField('press')),
                compressorObserv: this.cleanSelect(this.getValueField('compressor')),
                weldingMachineObserv: this.cleanSelect(this.getValueField('weldingMachine')),
                polisherObserv: this.cleanSelect(this.getValueField('polisher')),
                employeeObserv: this.cleanSelect(this.getValueField('employee')),
                gasCuttingEquipmentObserv: this.cleanSelect(this.getValueField('gasCuttingEquipment')),
                handsawObserv: this.cleanSelect(this.getValueField('handsaw')),
                vibrocompactadorObserv: this.cleanSelect(this.getValueField('vibrocompactador')),
                mixerObserv: this.cleanSelect(this.getValueField('mixer')),
                submersiblePumpObserv: this.cleanSelect(this.getValueField('submersiblePump')),
                pressureWasherObserv: this.cleanSelect(this.getValueField('pressureWasher')),
                doubleHandleHammerDrillObserv: this.cleanSelect(this.getValueField('doubleHandleHammerDrill')),
                marshlandObserv: this.cleanSelect(this.getValueField('marshland')),
                singleDrillAObserv: this.cleanSelect(this.getValueField('singleDrillA')),
                sanderObserv: this.cleanSelect(this.getValueField('sander')),
                smallPolisherAObserv: this.cleanSelect(this.getValueField('smallPolisherA')),
                largePolisherBObserv: this.cleanSelect(this.getValueField('largePolisherB')),
                shearsObserv: this.cleanSelect(this.getValueField('shears')),
                bigHammerObserv: this.cleanSelect(this.getValueField('bigHammer')),
                hammersObserv: this.cleanSelect(this.getValueField('hammers')),
                knivesObserv: this.cleanSelect(this.getValueField('knives')),
                fixedLadderObserv: this.cleanSelect(this.getValueField('fixedLadder')),
                macheteObserv: this.cleanSelect(this.getValueField('machete')),
                gustsObserv: this.cleanSelect(this.getValueField('gusts')),
                drillBitsObserv: this.cleanSelect(this.getValueField('drillBits')),
                fixedWrenchesObserv: this.cleanSelect(this.getValueField('fixedWrenches')),
                electricalTweezersObserv: this.cleanSelect(this.getValueField('electricalTweezers')),
                needleNoseTweezersObserv: this.cleanSelect(this.getValueField('needleNoseTweezers')),
                screwdriversObserv: this.cleanSelect(this.getValueField('screwdrivers')),
                decametersObserv: this.cleanSelect(this.getValueField('fixedLadder')),
                tapeMeasuresObserv: this.cleanSelect(this.getValueField('tapeMeasures')),
                needleNosePlierssObserv: this.cleanSelect(this.getValueField('tapeMeasures'))
            });
        }
    }


    onSubmit(): void {
        this.validationSubmit();
    }

}
