import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { ApiService } from 'app/services/api.service';
import { ControllerFormsComponent } from '../controller-forms.Component';
import { MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-sgfr86',
  templateUrl: './sgfr86.component.html',
  styleUrls: ['./sgfr86.component.scss']
})
export class Sgfr86Component extends ControllerFormsComponent implements OnInit {

    override code = 'SG-FR-86';
    override id = this.activatedRouter.snapshot?.paramMap.get('id');
    image: string  = './assets/images/forms/sgfr86.png';

    constructor(protected router: Router,
        protected _formBuilder: FormBuilder,
        protected activatedRouter: ActivatedRoute,
        protected matDialog: MatDialog,
        protected api: ApiService
    ) {
        super(_formBuilder, matDialog, api);
    }

    override ngOnInit(): void {
        super.ngOnInit();
        this.validateForm();
        this.getProject();
        this.getEmployees();
    }

    validateForm(): void {
        this.formInit = this._formBuilder.group({
            code: new FormControl({ value: this.code, disabled: true }),
            uid: new FormControl(),
            name: new FormControl(this.title),
            version: new FormControl({ value:'1.0', disabled: true }),
            company: new FormControl(1),
            fields: new FormArray([
                this._formBuilder.group({ name: 'location', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'operatorName', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'brand', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'serial', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'manufacturingModel', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'inspectionResult', value:   '', type: this.getTypeValue(1) }),
                this._formBuilder.group({ name: 'observations', value:   '', type: this.getTypeValue(1) }),

                this._formBuilder.group({ name: 'generalConditionMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'electricalSystemMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'coolingSystemConditionsMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'operationControlPanelMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'testingDifferentialCircuitBreakerMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'ignitionStatusMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'engineOperationMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'energySourceMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'conditionCablesMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'insulationSystemMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionSystemMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'groundMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'caliperStatusMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'weldingMaskMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'breastplateLeatherApronLegGaitersMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'safetyGlassesMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'glovesMonday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'faceShieldMonday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'generalConditionTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'electricalSystemTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'coolingSystemConditionsTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'operationControlPanelTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'testingDifferentialCircuitBreakerTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'ignitionStatusTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'engineOperationTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'energySourceTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'conditionCablesTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'insulationSystemTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionSystemTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'groundTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'caliperStatusTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'weldingMaskTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'breastplateLeatherApronLegGaitersTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'safetyGlassesTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'glovesTuesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'faceShieldTuesday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'generalConditionWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'electricalSystemWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'coolingSystemConditionsWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'operationControlPanelWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'testingDifferentialCircuitBreakerWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'ignitionStatusWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'engineOperationWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'energySourceWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'conditionCablesWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'insulationSystemWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionSystemWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'groundWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'caliperStatusWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'weldingMaskWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'breastplateLeatherApronLegGaitersWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'safetyGlassesWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'glovesWednesday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'faceShieldWednesday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'generalConditionThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'electricalSystemThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'coolingSystemConditionsThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'operationControlPanelThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'testingDifferentialCircuitBreakerThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'ignitionStatusThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'engineOperationThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'energySourceThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'conditionCablesThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'insulationSystemThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionSystemThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'groundThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'caliperStatusThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'weldingMaskThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'breastplateLeatherApronLegGaitersThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'safetyGlassesThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'glovesThursday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'faceShieldThursday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'generalConditionFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'electricalSystemFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'coolingSystemConditionsFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'operationControlPanelFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'testingDifferentialCircuitBreakerFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'ignitionStatusFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'engineOperationFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'energySourceFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'conditionCablesFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'insulationSystemFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionSystemFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'groundFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'caliperStatusFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'weldingMaskFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'breastplateLeatherApronLegGaitersFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'safetyGlassesFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'glovesFriday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'faceShieldFriday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'generalConditionSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'electricalSystemSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'coolingSystemConditionsSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'operationControlPanelSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'testingDifferentialCircuitBreakerSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'ignitionStatusSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'engineOperationSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'energySourceSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'conditionCablesSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'insulationSystemSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionSystemSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'groundSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'caliperStatusSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'weldingMaskSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'breastplateLeatherApronLegGaitersSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'safetyGlassesSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'glovesSaturday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'faceShieldSaturday', value:   '', type: this.getTypeValue(5) }),

                this._formBuilder.group({ name: 'generalConditionSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'electricalSystemSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'coolingSystemConditionsSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'operationControlPanelSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'testingDifferentialCircuitBreakerSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'ignitionStatusSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'engineOperationSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'energySourceSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'conditionCablesSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'insulationSystemSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'connectionSystemSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'groundSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'caliperStatusSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'weldingMaskSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'breastplateLeatherApronLegGaitersSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'safetyGlassesSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'glovesSunday', value:   '', type: this.getTypeValue(5) }),
                this._formBuilder.group({ name: 'faceShieldSunday', value:   '', type: this.getTypeValue(5) })
            ]),
            evidences: new FormControl([]),
            project: new FormControl('', [Validators.required]),
            assistants: new FormControl([]),
            approval: new FormControl([]),
            fieldsItems: this._formBuilder.group({
                location: new FormControl(''),
                operatorName: new FormControl(''),
                brand: new FormControl(''),
                serial: new FormControl(''),
                manufacturingModel: new FormControl(''),
                inspectionResult: new FormControl(''),
                observations: new FormControl(''),

                generalConditionMonday: new FormControl(),
                electricalSystemMonday: new FormControl(),
                coolingSystemConditionsMonday: new FormControl(),
                operationControlPanelMonday: new FormControl(),
                testingDifferentialCircuitBreakerMonday: new FormControl(),
                ignitionStatusMonday: new FormControl(),
                engineOperationMonday: new FormControl(),
                energySourceMonday: new FormControl(),
                conditionCablesMonday: new FormControl(),
                insulationSystemMonday: new FormControl(),
                connectionSystemMonday: new FormControl(),
                groundMonday: new FormControl(),
                caliperStatusMonday: new FormControl(),
                weldingMaskMonday: new FormControl(),
                breastplateLeatherApronLegGaitersMonday: new FormControl(),
                safetyGlassesMonday: new FormControl(),
                glovesMonday: new FormControl(),
                faceShieldMonday: new FormControl(),

                generalConditionTuesday: new FormControl(),
                electricalSystemTuesday: new FormControl(),
                coolingSystemConditionsTuesday: new FormControl(),
                operationControlPanelTuesday: new FormControl(),
                testingDifferentialCircuitBreakerTuesday: new FormControl(),
                ignitionStatusTuesday: new FormControl(),
                engineOperationTuesday: new FormControl(),
                energySourceTuesday: new FormControl(),
                conditionCablesTuesday: new FormControl(),
                insulationSystemTuesday: new FormControl(),
                connectionSystemTuesday: new FormControl(),
                groundTuesday: new FormControl(),
                caliperStatusTuesday: new FormControl(),
                weldingMaskTuesday: new FormControl(),
                breastplateLeatherApronLegGaitersTuesday: new FormControl(),
                safetyGlassesTuesday: new FormControl(),
                glovesTuesday: new FormControl(),
                faceShieldTuesday: new FormControl(),

                generalConditionWednesday: new FormControl(),
                electricalSystemWednesday: new FormControl(),
                coolingSystemConditionsWednesday: new FormControl(),
                operationControlPanelWednesday: new FormControl(),
                testingDifferentialCircuitBreakerWednesday: new FormControl(),
                ignitionStatusWednesday: new FormControl(),
                engineOperationWednesday: new FormControl(),
                energySourceWednesday: new FormControl(),
                conditionCablesWednesday: new FormControl(),
                insulationSystemWednesday: new FormControl(),
                connectionSystemWednesday: new FormControl(),
                groundWednesday: new FormControl(),
                caliperStatusWednesday: new FormControl(),
                weldingMaskWednesday: new FormControl(),
                breastplateLeatherApronLegGaitersWednesday: new FormControl(),
                safetyGlassesWednesday: new FormControl(),
                glovesWednesday: new FormControl(),
                faceShieldWednesday: new FormControl(),

                generalConditionThursday: new FormControl(),
                electricalSystemThursday: new FormControl(),
                coolingSystemConditionsThursday: new FormControl(),
                operationControlPanelThursday: new FormControl(),
                testingDifferentialCircuitBreakerThursday: new FormControl(),
                ignitionStatusThursday: new FormControl(),
                engineOperationThursday: new FormControl(),
                energySourceThursday: new FormControl(),
                conditionCablesThursday: new FormControl(),
                insulationSystemThursday: new FormControl(),
                connectionSystemThursday: new FormControl(),
                groundThursday: new FormControl(),
                caliperStatusThursday: new FormControl(),
                weldingMaskThursday: new FormControl(),
                breastplateLeatherApronLegGaitersThursday: new FormControl(),
                safetyGlassesThursday: new FormControl(),
                glovesThursday: new FormControl(),
                faceShieldThursday: new FormControl(),

                generalConditionFriday: new FormControl(),
                electricalSystemFriday: new FormControl(),
                coolingSystemConditionsFriday: new FormControl(),
                operationControlPanelFriday: new FormControl(),
                testingDifferentialCircuitBreakerFriday: new FormControl(),
                ignitionStatusFriday: new FormControl(),
                engineOperationFriday: new FormControl(),
                energySourceFriday: new FormControl(),
                conditionCablesFriday: new FormControl(),
                insulationSystemFriday: new FormControl(),
                connectionSystemFriday: new FormControl(),
                groundFriday: new FormControl(),
                caliperStatusFriday: new FormControl(),
                weldingMaskFriday: new FormControl(),
                breastplateLeatherApronLegGaitersFriday: new FormControl(),
                safetyGlassesFriday: new FormControl(),
                glovesFriday: new FormControl(),
                faceShieldFriday: new FormControl(),

                generalConditionSaturday: new FormControl(),
                electricalSystemSaturday: new FormControl(),
                coolingSystemConditionsSaturday: new FormControl(),
                operationControlPanelSaturday: new FormControl(),
                testingDifferentialCircuitBreakerSaturday: new FormControl(),
                ignitionStatusSaturday: new FormControl(),
                engineOperationSaturday: new FormControl(),
                energySourceSaturday: new FormControl(),
                conditionCablesSaturday: new FormControl(),
                insulationSystemSaturday: new FormControl(),
                connectionSystemSaturday: new FormControl(),
                groundSaturday: new FormControl(),
                caliperStatusSaturday: new FormControl(),
                weldingMaskSaturday: new FormControl(),
                breastplateLeatherApronLegGaitersSaturday: new FormControl(),
                safetyGlassesSaturday: new FormControl(),
                glovesSaturday: new FormControl(),
                faceShieldSaturday: new FormControl(),

                generalConditionSunday: new FormControl(),
                electricalSystemSunday: new FormControl(),
                coolingSystemConditionsSunday: new FormControl(),
                operationControlPanelSunday: new FormControl(),
                testingDifferentialCircuitBreakerSunday: new FormControl(),
                ignitionStatusSunday: new FormControl(),
                engineOperationSunday: new FormControl(),
                energySourceSunday: new FormControl(),
                conditionCablesSunday: new FormControl(),
                insulationSystemSunday: new FormControl(),
                connectionSystemSunday: new FormControl(),
                groundSunday: new FormControl(),
                caliperStatusSunday: new FormControl(),
                weldingMaskSunday: new FormControl(),
                breastplateLeatherApronLegGaitersSunday: new FormControl(),
                safetyGlassesSunday: new FormControl(),
                glovesSunday: new FormControl(),
                faceShieldSunday: new FormControl(),


            }),
            filesUpload: new FormControl(),
            assignedAssistants: new FormControl(),
            trainingApproval: new FormControl()
        });
    }

    override getForm(): void {
        if (this.id) {
            this.formInit.get('fieldsItems').patchValue({
                location: this.cleanSelect(this.getValueField('location')),
                operatorName: this.cleanSelect(this.getValueField('operatorName')),
                brand: this.cleanSelect(this.getValueField('brand')),
                serial: this.cleanSelect(this.getValueField('serial')),
                manufacturingModel: this.cleanSelect(this.getValueField('manufacturingModel')),
                inspectionResult: this.cleanSelect(this.getValueField('inspectionResult')),
                observations: this.cleanSelect(this.getValueField('observations')),

                generalConditionMonday: this.cleanSelect(this.getValueField('generalConditionMonday')),
                electricalSystemMonday: this.cleanSelect(this.getValueField('electricalSystemMonday')),
                coolingSystemConditionsMonday: this.cleanSelect(this.getValueField('coolingSystemConditionsMonday')),
                operationControlPanelMonday: this.cleanSelect(this.getValueField('operationControlPanelMonday')),
                testingDifferentialCircuitBreakerMonday: this.cleanSelect(this.getValueField('testingDifferentialCircuitBreakerMonday')),
                ignitionStatusMonday: this.cleanSelect(this.getValueField('ignitionStatusMonday')),
                engineOperationMonday: this.cleanSelect(this.getValueField('engineOperationMonday')),
                energySourceMonday: this.cleanSelect(this.getValueField('energySourceMonday')),
                conditionCablesMonday: this.cleanSelect(this.getValueField('conditionCablesMonday')),
                insulationSystemMonday: this.cleanSelect(this.getValueField('insulationSystemMonday')),
                connectionSystemMonday: this.cleanSelect(this.getValueField('connectionSystemMonday')),
                groundMonday: this.cleanSelect(this.getValueField('groundMonday')),
                caliperStatusMonday: this.cleanSelect(this.getValueField('caliperStatusMonday')),
                weldingMaskMonday: this.cleanSelect(this.getValueField('electricalSystemMonday')),
                breastplateLeatherApronLegGaitersMonday: this.cleanSelect(this.getValueField('coolingSystemConditionsMonday')),
                safetyGlassesMonday: this.cleanSelect(this.getValueField('operationControlPanelMonday')),
                glovesMonday: this.cleanSelect(this.getValueField('generalConditionMonday')),
                faceShieldMonday: this.cleanSelect(this.getValueField('electricalSystemMonday')),

                generalConditionTuesday: this.cleanSelect(this.getValueField('generalConditionTuesday')),
                electricalSystemTuesday: this.cleanSelect(this.getValueField('electricalSystemTuesday')),
                coolingSystemConditionsTuesday: this.cleanSelect(this.getValueField('coolingSystemConditionsTuesday')),
                operationControlPanelTuesday: this.cleanSelect(this.getValueField('operationControlPanelTuesday')),
                testingDifferentialCircuitBreakerTuesday: this.cleanSelect(this.getValueField('testingDifferentialCircuitBreakerTuesday')),
                ignitionStatusTuesday: this.cleanSelect(this.getValueField('ignitionStatusTuesday')),
                engineOperationTuesday: this.cleanSelect(this.getValueField('engineOperationTuesday')),
                energySourceTuesday: this.cleanSelect(this.getValueField('energySourceTuesday')),
                conditionCablesTuesday: this.cleanSelect(this.getValueField('conditionCablesTuesday')),
                insulationSystemTuesday: this.cleanSelect(this.getValueField('insulationSystemTuesday')),
                connectionSystemTuesday: this.cleanSelect(this.getValueField('connectionSystemTuesday')),
                groundTuesday: this.cleanSelect(this.getValueField('groundTuesday')),
                caliperStatusTuesday: this.cleanSelect(this.getValueField('caliperStatusTuesday')),
                weldingMaskTuesday: this.cleanSelect(this.getValueField('electricalSystemTuesday')),
                breastplateLeatherApronLegGaitersTuesday: this.cleanSelect(this.getValueField('coolingSystemConditionsTuesday')),
                safetyGlassesTuesday: this.cleanSelect(this.getValueField('operationControlPanelTuesday')),
                glovesTuesday: this.cleanSelect(this.getValueField('generalConditionTuesday')),
                faceShieldTuesday: this.cleanSelect(this.getValueField('electricalSystemTuesday')),

                generalConditionWednesday: this.cleanSelect(this.getValueField('generalConditionWednesday')),
                electricalSystemWednesday: this.cleanSelect(this.getValueField('electricalSystemWednesday')),
                coolingSystemConditionsWednesday: this.cleanSelect(this.getValueField('coolingSystemConditionsWednesday')),
                operationControlPanelWednesday: this.cleanSelect(this.getValueField('operationControlPanelWednesday')),
                testingDifferentialCircuitBreakerWednesday: this.cleanSelect(this.getValueField('testingDifferentialCircuitBreakerWednesday')),
                ignitionStatusWednesday: this.cleanSelect(this.getValueField('ignitionStatusWednesday')),
                engineOperationWednesday: this.cleanSelect(this.getValueField('engineOperationWednesday')),
                energySourceWednesday: this.cleanSelect(this.getValueField('energySourceWednesday')),
                conditionCablesWednesday: this.cleanSelect(this.getValueField('conditionCablesWednesday')),
                insulationSystemWednesday: this.cleanSelect(this.getValueField('insulationSystemWednesday')),
                connectionSystemWednesday: this.cleanSelect(this.getValueField('connectionSystemWednesday')),
                groundWednesday: this.cleanSelect(this.getValueField('groundWednesday')),
                caliperStatusWednesday: this.cleanSelect(this.getValueField('caliperStatusWednesday')),
                weldingMaskWednesday: this.cleanSelect(this.getValueField('electricalSystemWednesday')),
                breastplateLeatherApronLegGaitersWednesday: this.cleanSelect(this.getValueField('coolingSystemConditionsWednesday')),
                safetyGlassesWednesday: this.cleanSelect(this.getValueField('operationControlPanelWednesday')),
                glovesWednesday: this.cleanSelect(this.getValueField('generalConditionWednesday')),
                faceShieldWednesday: this.cleanSelect(this.getValueField('electricalSystemWednesday')),

                generalConditionThursday: this.cleanSelect(this.getValueField('generalConditionThursday')),
                electricalSystemThursday: this.cleanSelect(this.getValueField('electricalSystemThursday')),
                coolingSystemConditionsThursday: this.cleanSelect(this.getValueField('coolingSystemConditionsThursday')),
                operationControlPanelThursday: this.cleanSelect(this.getValueField('operationControlPanelThursday')),
                testingDifferentialCircuitBreakerThursday: this.cleanSelect(this.getValueField('testingDifferentialCircuitBreakerThursday')),
                ignitionStatusThursday: this.cleanSelect(this.getValueField('ignitionStatusThursday')),
                engineOperationThursday: this.cleanSelect(this.getValueField('engineOperationThursday')),
                energySourceThursday: this.cleanSelect(this.getValueField('energySourceThursday')),
                conditionCablesThursday: this.cleanSelect(this.getValueField('conditionCablesThursday')),
                insulationSystemThursday: this.cleanSelect(this.getValueField('insulationSystemThursday')),
                connectionSystemThursday: this.cleanSelect(this.getValueField('connectionSystemThursday')),
                groundThursday: this.cleanSelect(this.getValueField('groundThursday')),
                caliperStatusThursday: this.cleanSelect(this.getValueField('caliperStatusThursday')),
                weldingMaskThursday: this.cleanSelect(this.getValueField('electricalSystemThursday')),
                breastplateLeatherApronLegGaitersThursday: this.cleanSelect(this.getValueField('coolingSystemConditionsThursday')),
                safetyGlassesThursday: this.cleanSelect(this.getValueField('operationControlPanelThursday')),
                glovesThursday: this.cleanSelect(this.getValueField('generalConditionThursday')),
                faceShieldThursday: this.cleanSelect(this.getValueField('electricalSystemThursday')),

                generalConditionFriday: this.cleanSelect(this.getValueField('generalConditionFriday')),
                electricalSystemFriday: this.cleanSelect(this.getValueField('electricalSystemFriday')),
                coolingSystemConditionsFriday: this.cleanSelect(this.getValueField('coolingSystemConditionsFriday')),
                operationControlPanelFriday: this.cleanSelect(this.getValueField('operationControlPanelFriday')),
                testingDifferentialCircuitBreakerFriday: this.cleanSelect(this.getValueField('testingDifferentialCircuitBreakerFriday')),
                ignitionStatusFriday: this.cleanSelect(this.getValueField('ignitionStatusFriday')),
                engineOperationFriday: this.cleanSelect(this.getValueField('engineOperationFriday')),
                energySourceFriday: this.cleanSelect(this.getValueField('energySourceFriday')),
                conditionCablesFriday: this.cleanSelect(this.getValueField('conditionCablesFriday')),
                insulationSystemFriday: this.cleanSelect(this.getValueField('insulationSystemFriday')),
                connectionSystemFriday: this.cleanSelect(this.getValueField('connectionSystemFriday')),
                groundFriday: this.cleanSelect(this.getValueField('groundFriday')),
                caliperStatusFriday: this.cleanSelect(this.getValueField('caliperStatusFriday')),
                weldingMaskFriday: this.cleanSelect(this.getValueField('electricalSystemFriday')),
                breastplateLeatherApronLegGaitersFriday: this.cleanSelect(this.getValueField('coolingSystemConditionsFriday')),
                safetyGlassesFriday: this.cleanSelect(this.getValueField('operationControlPanelFriday')),
                glovesFriday: this.cleanSelect(this.getValueField('generalConditionFriday')),
                faceShieldFriday: this.cleanSelect(this.getValueField('electricalSystemFriday')),

                generalConditionSaturday: this.cleanSelect(this.getValueField('generalConditionSaturday')),
                electricalSystemSaturday: this.cleanSelect(this.getValueField('electricalSystemSaturday')),
                coolingSystemConditionsSaturday: this.cleanSelect(this.getValueField('coolingSystemConditionsSaturday')),
                operationControlPanelSaturday: this.cleanSelect(this.getValueField('operationControlPanelSaturday')),
                testingDifferentialCircuitBreakerSaturday: this.cleanSelect(this.getValueField('testingDifferentialCircuitBreakerSaturday')),
                ignitionStatusSaturday: this.cleanSelect(this.getValueField('ignitionStatusSaturday')),
                engineOperationSaturday: this.cleanSelect(this.getValueField('engineOperationSaturday')),
                energySourceSaturday: this.cleanSelect(this.getValueField('energySourceSaturday')),
                conditionCablesSaturday: this.cleanSelect(this.getValueField('conditionCablesSaturday')),
                insulationSystemSaturday: this.cleanSelect(this.getValueField('insulationSystemSaturday')),
                connectionSystemSaturday: this.cleanSelect(this.getValueField('connectionSystemSaturday')),
                groundSaturday: this.cleanSelect(this.getValueField('groundSaturday')),
                caliperStatusSaturday: this.cleanSelect(this.getValueField('caliperStatusSaturday')),
                weldingMaskSaturday: this.cleanSelect(this.getValueField('electricalSystemSaturday')),
                breastplateLeatherApronLegGaitersSaturday: this.cleanSelect(this.getValueField('coolingSystemConditionsSaturday')),
                safetyGlassesSaturday: this.cleanSelect(this.getValueField('operationControlPanelSaturday')),
                glovesSaturday: this.cleanSelect(this.getValueField('generalConditionSaturday')),
                faceShieldSaturday: this.cleanSelect(this.getValueField('electricalSystemSaturday')),

                generalConditionSunday: this.cleanSelect(this.getValueField('generalConditionSunday')),
                electricalSystemSunday: this.cleanSelect(this.getValueField('electricalSystemSunday')),
                coolingSystemConditionsSunday: this.cleanSelect(this.getValueField('coolingSystemConditionsSunday')),
                operationControlPanelSunday: this.cleanSelect(this.getValueField('operationControlPanelSunday')),
                testingDifferentialCircuitBreakerSunday: this.cleanSelect(this.getValueField('testingDifferentialCircuitBreakerSunday')),
                ignitionStatusSunday: this.cleanSelect(this.getValueField('ignitionStatusSunday')),
                engineOperationSunday: this.cleanSelect(this.getValueField('engineOperationSunday')),
                energySourceSunday: this.cleanSelect(this.getValueField('energySourceSunday')),
                conditionCablesSunday: this.cleanSelect(this.getValueField('conditionCablesSunday')),
                insulationSystemSunday: this.cleanSelect(this.getValueField('insulationSystemSunday')),
                connectionSystemSunday: this.cleanSelect(this.getValueField('connectionSystemSunday')),
                groundSunday: this.cleanSelect(this.getValueField('groundSunday')),
                caliperStatusSunday: this.cleanSelect(this.getValueField('caliperStatusSunday')),
                weldingMaskSunday: this.cleanSelect(this.getValueField('electricalSystemSunday')),
                breastplateLeatherApronLegGaitersSunday: this.cleanSelect(this.getValueField('coolingSystemConditionsSunday')),
                safetyGlassesSunday: this.cleanSelect(this.getValueField('operationControlPanelSunday')),
                glovesSunday: this.cleanSelect(this.getValueField('generalConditionSunday')),
                faceShieldSunday: this.cleanSelect(this.getValueField('electricalSystemSunday'))
            });
        }
    }

    filterParamLabel(param): void{
        return this.getLabel(param);
    }

    filterParamValue(param): void{
        return this.getParamLabel(param);
    }

    onSubmit(): void {
        this.validationSubmit();
    }

}
